version: '3.3'

services:
  jmeter-influxdb:
    container_name: jmeter-influxdb
    image: influxdb:1.8
    restart: always
    environment:
        INFLUXDB_GRAPHITE_ENABLED: "true"
        INFLUXDB_DB: "jmeter"
    # volumes:
    #   - "/var/lib/influxdb:/var/lib/influxdb"
    ports:
      - "${INFLUX_API_PORT}:8086"
      - "${INFLUX_GRAPHITE_PORT}:2003"
    expose:
      - "8086"
      - "2003"

  jmeter-grafana:
    links:
      - jmeter-influxdb
    container_name: jmeter-grafana
    image: grafana/grafana:7.0.0
    restart: always
    ports:
      - "${GRAFANA_PORT}:3000"
    expose:
      - "3000"
  
  # jmeter:
  #   network_mode: "bridge"
  #   links:
  #     - influxdb
  #   container_name: "jmeter"
  #   image: egaillardon/jmeter
  #   restart: always
  #   command: -Jserver.rmi.ssl.disable=true -Djava.rmi.server.hostname=${HOST} -Jserver.rmi.localport=${PORT} --server
  #   ports:
  #     - "${PORT}:${PORT}"
  #   expose:
  #     - "${PORT}"

